
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [pln].[vw_DimDate]
AS

SELECT [YearID]
      ,[QuarterID]
      ,[MonthID]
      ,[WeekID]
      ,SUM([Workdays]) AS [Workdays]
      ,SUM([DaysCount]) AS [DaysCount]
      ,[MonthNr]
      ,[MonthNameDE]
      ,[MonthShortNameDE]
      ,[MonthNameEN]
      ,[MonthShortNameEN]
      ,[QuarterNr]
      ,[QuarterText]
      ,[CalendarWeekText]
      ,[LastDayOfMonth]
      ,[DaysInMonth]
      ,[FirstDayOfWeek]
      ,[LastDayOfWeek]
      ,[MonthNext]
      ,[MonthPrev]
      ,[YearNext]
      ,[YearPrev]
      ,[CalenderWeekIDNext]
      ,[CalenderWeekIDPrev]
      ,MIN([WeekNext]) AS [WeekNext]
      ,MIN([WeekPrev]) AS [WeekPrev]
      ,[QuarterNext]
      ,[QuarterPrev]
  FROM [pln].[vw_DimDateExtended]
  GROUP BY
  [YearID]
      ,[QuarterID]
      ,[MonthID]
      ,[WeekID]
      ,[MonthNr]
      ,[MonthNameDE]
      ,[MonthShortNameDE]
      ,[MonthNameEN]
      ,[MonthShortNameEN]
      ,[QuarterNr]
      ,[QuarterText]
      ,[CalendarWeekText]
      ,[LastDayOfMonth]
      ,[DaysInMonth]
      ,[FirstDayOfWeek]
      ,[LastDayOfWeek]
      ,[MonthNext]
      ,[MonthPrev]
      ,[YearNext]
      ,[YearPrev]
      ,[CalenderWeekIDNext]
      ,[CalenderWeekIDPrev]
      ,[QuarterNext]
      ,[QuarterPrev]

