{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"vw_DimAbsenceType\",\"vw_DimCustomer\",\"vw_DimDate\",\"vw_DimProject\",\"vw_DimProjectTask\",\"vw_DimProjectRole\",\"vw_DimSprint\",\"vw_DimUser\",\"Dim Absence\",\"Dim Customer\",\"Dim Date\",\"Dim Deal\",\"Dim Date Visualiation\",\"Dim Jira Issue\",\"Dim Project\",\"Dim Project Role\",\"Dim Project Task\",\"Dim Sprint\",\"Dim User\",\"Fact Capacity\",\"Fact Budget\",\"Fact Budget Days\",\"Fact Plan\",\"Fact Invoice\",\"Fact Jira Issue\",\"Fact Worklog\",\"Helper Duplikate\",\"_Measures\",\"vw_FactCapacity\",\"vw_FactInvoice\",\"vw_FactJiraIssue\",\"vw_FactWorklog\",\"vw_FactPlan\",\"vw_DimDeal\",\"vw_FactBudget\",\"vw_FactBudgetDays\",\"Dim Budget Category\",\"vw_DimJiraIssue\",\"Dim Sprint Visualiation\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.927.0 (24.02)"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "vw_DimDate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimDate = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimDate\"]}[Data],",
          "    #\"Gefilterte Zeilen\" = Table.SelectRows(pbi_vw_DimDate, each ([YearID] = 2020 or [YearID] = 2021 or [YearID] = 2022 or [YearID] = 2023 or [YearID] = 2024 or [YearID] = 2025)),",
          "    #\"Entfernte Duplikate\" = Table.Distinct(#\"Gefilterte Zeilen\", {\"DateBK\"})",
          "in",
          "    #\"Entfernte Duplikate\""
        ],
        "kind": "m",
        "lineageTag": "7494d19a-d380-40e0-a37a-633b49449efb",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_DimSprint",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimSprint = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimSprint\"]}[Data]",
          "in",
          "    pbi_vw_DimSprint"
        ],
        "kind": "m",
        "lineageTag": "92e93469-2c84-45b7-80e4-9d5a6def2615",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_DimUser",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimUser = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimUser\"]}[Data]",
          "in",
          "    pbi_vw_DimUser"
        ],
        "kind": "m",
        "lineageTag": "e5ab1065-ef35-440f-9857-be020a27013f",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_DimProject",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimDate = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimProject\"]}[Data]",
          "in",
          "    pbi_vw_DimDate"
        ],
        "kind": "m",
        "lineageTag": "775b8908-3d99-4b26-89b5-3b1acc75a825",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_DimCustomer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimDate = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimCustomer\"]}[Data]",
          "in",
          "    pbi_vw_DimDate"
        ],
        "kind": "m",
        "lineageTag": "c00c8719-879e-4cc1-8756-a50688c05694",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_FactJiraIssue",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimUser = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactJiraIssue\"]}[Data]",
          "in",
          "    pbi_vw_DimUser"
        ],
        "kind": "m",
        "lineageTag": "743acdf7-5734-4868-b078-468e65397e28",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_FactWorklog",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_FactWorklog = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactWorklogSmall\"]}[Data]",
          "in",
          "    pbi_vw_FactWorklog"
        ],
        "kind": "m",
        "lineageTag": "25279027-9456-41ca-9602-0ca932308384",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_DimAbsenceType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimAbsenceType = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimAbsence\"]}[Data]",
          "in",
          "    pbi_vw_DimAbsenceType"
        ],
        "kind": "m",
        "lineageTag": "f27275f5-f58c-4a23-a2d7-a1ede00daba8",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_DimProjectRole",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimProjectRole = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimProjectRole\"]}[Data]",
          "in",
          "    pbi_vw_DimProjectRole"
        ],
        "kind": "m",
        "lineageTag": "91968ef8-7901-4aed-9f33-d4b26884cf20",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_FactCapacity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_FactCapacity = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactCapacity\"]}[Data]",
          "in",
          "    pbi_vw_FactCapacity"
        ],
        "kind": "m",
        "lineageTag": "5730e9c0-0d1e-41b7-a1b7-b062c315abe4",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_FactInvoice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_FactInvoice = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactInvoice\"]}[Data]",
          "in",
          "    pbi_vw_FactInvoice"
        ],
        "kind": "m",
        "lineageTag": "11fc8761-5dd9-467f-b236-13b749eb045c",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_DimProjectTask",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimProjectTask = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimProjectTask\"]}[Data]",
          "in",
          "    pbi_vw_DimProjectTask"
        ],
        "kind": "m",
        "lineageTag": "5404a22e-5ead-4ea8-9e97-d0ba068f12d7",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_FactPlan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_FactBlueAntWorklog = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactPlan\"]}[Data]",
          "in",
          "    pbi_vw_FactBlueAntWorklog"
        ],
        "kind": "m",
        "lineageTag": "2fbcba26-2775-4e45-9895-e4c9a554a48d",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_DimDeal",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimDate = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimDeal\"]}[Data]",
          "in",
          "    pbi_vw_DimDate"
        ],
        "kind": "m",
        "lineageTag": "1250f6bb-3e2a-406f-8b6e-8f57a34328a5",
        "queryGroup": "Source\\Dim"
      },
      {
        "name": "vw_FactBudget",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_FactCapacity = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactBudget\"]}[Data]",
          "in",
          "    pbi_vw_FactCapacity"
        ],
        "kind": "m",
        "lineageTag": "ec9318fc-906a-4b93-80b1-96bb655342a8",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_FactBudgetDays",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_FactCapacity = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_FactBudgetDays\"]}[Data]",
          "in",
          "    pbi_vw_FactCapacity"
        ],
        "kind": "m",
        "lineageTag": "92354858-21c9-4dcb-8023-4389c9093e4b",
        "queryGroup": "Source\\Fact"
      },
      {
        "name": "vw_DimJiraIssue",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases(\"sql-dwh-prod-gt4645g.database.windows.net\"),",
          "    databaseceterisdwh = Source{[Name=\"sqldb-dwh-prod-gt4645g\"]}[Data],",
          "    pbi_vw_DimSprint = databaseceterisdwh{[Schema=\"pbi\",Item=\"vw_DimJiraIssue\"]}[Data]",
          "in",
          "    pbi_vw_DimSprint"
        ],
        "kind": "m",
        "lineageTag": "50949aba-5637-4e39-a490-e0d516801e43",
        "queryGroup": "Source\\Dim"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source\\Dim"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Source\\Fact"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Model"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Model\\Dim"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Model\\Fact"
      }
    ],
    "relationships": [
      {
        "name": "9baa9925-c93e-4024-bd70-601fb3bd0af2",
        "fromColumn": "DateID",
        "fromTable": "Fact Capacity",
        "toColumn": "DateID",
        "toTable": "Dim Date"
      },
      {
        "name": "546e0181-de40-4c95-b645-3dfa807431bf",
        "fromColumn": "UserID",
        "fromTable": "Fact Capacity",
        "toColumn": "UserID",
        "toTable": "Dim User"
      },
      {
        "name": "050bd821-dcf1-4298-bacf-3d7b89b1bb3c",
        "fromColumn": "DateID",
        "fromTable": "Fact Capacity",
        "toColumn": "DateID",
        "toTable": "Dim Date Visualiation"
      },
      {
        "name": "d00e7021-5350-4b88-b293-a0dbd92b6cf3",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Fact Invoice",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "1f59b998-629c-4e14-84e9-c355b7b7f007",
        "fromColumn": "InvoiceDateID",
        "fromTable": "Fact Invoice",
        "toColumn": "DateID",
        "toTable": "Dim Date"
      },
      {
        "name": "f9a2a282-86d8-4895-bbe8-473e2b7689cd",
        "fromColumn": "UserID",
        "fromTable": "Fact Worklog",
        "toColumn": "UserID",
        "toTable": "Dim User"
      },
      {
        "name": "92c4454d-5e16-403b-b836-80fc6b42bd0b",
        "fromColumn": "DateID",
        "fromTable": "Fact Worklog",
        "toColumn": "DateID",
        "toTable": "Dim Date"
      },
      {
        "name": "0d471b10-257d-4338-adb8-a427accb5c6e",
        "fromColumn": "DateID",
        "fromTable": "Fact Worklog",
        "toColumn": "DateID",
        "toTable": "Dim Date Visualiation"
      },
      {
        "name": "ba802374-dce8-43a0-8531-ad7d08030b49",
        "fromColumn": "CustomerID",
        "fromTable": "Dim Project",
        "toColumn": "BlueAntCustomerID",
        "toTable": "Dim Customer"
      },
      {
        "name": "3ebf829d-8648-4418-87fb-a7f090590efa",
        "fromColumn": "InvoiceDateID",
        "fromTable": "Fact Invoice",
        "toColumn": "DateID",
        "toTable": "Dim Date Visualiation"
      },
      {
        "name": "28968f7d-8a37-497b-8ab0-a4017054e6b0",
        "fromColumn": "BlueAntProjectTaskID",
        "fromTable": "Fact Worklog",
        "toColumn": "BlueAntProjectTaskID",
        "toTable": "Dim Project Task"
      },
      {
        "name": "746645af-d131-4e19-8a4c-3401db8de388",
        "fromColumn": "DateID",
        "fromTable": "Dim Absence",
        "toColumn": "DateID",
        "toTable": "Dim Date Visualiation"
      },
      {
        "name": "d1218f10-7a32-46bc-b440-1cae0097f3c0",
        "fromColumn": "DateID",
        "fromTable": "Dim Absence",
        "toColumn": "DateID",
        "toTable": "Dim Date"
      },
      {
        "name": "c506c0b0-2b2e-466f-9aa7-a103efb6ebe7",
        "fromColumn": "UserID",
        "fromTable": "Dim Absence",
        "toColumn": "UserID",
        "toTable": "Dim User"
      },
      {
        "name": "750077bb-162c-4599-a21b-9b0414e42553",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Dim Project Task",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "bd09af46-e85e-4a6d-85dd-eae299193cc1",
        "fromColumn": "UserID",
        "fromTable": "Dim Project Role",
        "toColumn": "UserID",
        "toTable": "Dim User"
      },
      {
        "name": "5f18d96c-3451-4b86-a315-d93d144fee9c",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Dim Project Role",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "3877496c-8c4e-4025-a44a-e954ed787526",
        "fromColumn": "DateID",
        "fromTable": "Fact Plan",
        "toColumn": "DateID",
        "toTable": "Dim Date"
      },
      {
        "name": "fa627f52-7d2c-4008-9a4b-f5834d691d4a",
        "fromColumn": "DateID",
        "fromTable": "Fact Plan",
        "toColumn": "DateID",
        "toTable": "Dim Date Visualiation"
      },
      {
        "name": "0ae7a707-69c9-4a24-a6a2-5827ba8ca1a5",
        "fromColumn": "UserID",
        "fromTable": "Fact Plan",
        "toColumn": "UserID",
        "toTable": "Dim User"
      },
      {
        "name": "8de1499e-de6f-4eb0-b831-5fe9fbff7c80",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Fact Plan",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "ccd37af1-12a5-43e3-ab8e-0fb8a48b8250",
        "fromColumn": "DealID",
        "fromTable": "Fact Plan",
        "toColumn": "DealID",
        "toTable": "Dim Deal"
      },
      {
        "name": "84acb03c-65cf-4265-b1e1-265de68c3653",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Fact Budget Days",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "32e106a8-e968-4cc8-b4b4-9d1d8a9e789d",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Fact Budget",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "24d3876b-0bdc-4040-9aba-5c8ce9457104",
        "fromColumn": "Attribut",
        "fromTable": "Fact Budget Days",
        "toColumn": "Category",
        "toTable": "Dim Budget Category"
      },
      {
        "name": "f8d9549f-b869-459f-8151-052f55015f6b",
        "fromColumn": "Attribut",
        "fromTable": "Fact Budget",
        "toColumn": "Category",
        "toTable": "Dim Budget Category"
      },
      {
        "name": "27cffc1d-ccf4-4829-98b2-552d2d662500",
        "fromColumn": "JiraSprintID",
        "fromTable": "Dim Jira Issue",
        "toCardinality": "many",
        "toColumn": "JiraSprintID",
        "toTable": "Dim Sprint"
      },
      {
        "name": "04990fe9-d262-40a4-ac70-015f815d4d46",
        "fromColumn": "BlueAntProjectID",
        "fromTable": "Dim Jira Issue",
        "toColumn": "BlueAntProjectID",
        "toTable": "Dim Project"
      },
      {
        "name": "a329ff38-3669-41f0-ab36-8140146b9609",
        "fromColumn": "UserID",
        "fromTable": "Dim Jira Issue",
        "toColumn": "UserID",
        "toTable": "Dim User"
      },
      {
        "name": "c5686460-b632-4e62-8038-17b6af85e94c",
        "fromColumn": "JiraIssueID",
        "fromTable": "Fact Jira Issue",
        "toColumn": "JiraIssueID",
        "toTable": "Dim Jira Issue"
      },
      {
        "name": "750a07ca-0ba2-4e8c-87fc-f1d470709dcf",
        "fromColumn": "JiraSprintID",
        "fromTable": "Dim Date Visualiation",
        "toColumn": "JiraSprintID",
        "toTable": "Dim Sprint Visualiation"
      },
      {
        "name": "ebf3568f-fdb3-4277-ae86-9a6aee31e287",
        "fromColumn": "JiraSprintID",
        "fromTable": "Dim Date",
        "toColumn": "JiraSprintID",
        "toTable": "Dim Sprint"
      }
    ],
    "sourceQueryCulture": "de-DE",
    "tables": [
      {
        "name": "Dim Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1edfc39-4403-4539-a206-13ee530d5731",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "DateBK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "600f3a1e-515a-49ca-aa87-b35fccf75dd5",
            "sourceColumn": "DateBK",
            "summarizeBy": "none"
          },
          {
            "name": "DayID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c55aee23-9dce-423f-aac2-8ef3057f1486",
            "sourceColumn": "DayID",
            "summarizeBy": "none"
          },
          {
            "name": "MonthID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ed13749-9fc0-4cab-b44a-92d429c9dd3d",
            "sourceColumn": "MonthID",
            "summarizeBy": "none"
          },
          {
            "name": "YearID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d19ec89-3ef9-43bf-baae-598c8e9e23ac",
            "sourceColumn": "YearID",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "22e59f3f-9e93-475b-806c-96b560a4e331",
            "sortByColumn": "MonthID",
            "sourceColumn": "MonthNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "MonthShortNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f919ba8-8ba5-423d-8559-876796d475ad",
            "sortByColumn": "MonthID",
            "sourceColumn": "MonthShortNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da07c631-7114-48f4-ad3c-55393420e6c7",
            "sourceColumn": "WeekdayID",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "26e39e43-94b5-4433-ba48-7dd7e4b28ab4",
            "sortByColumn": "WeekdayID",
            "sourceColumn": "WeekdayNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayShortNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ed53de3-b60a-468e-b93e-58a8b971a745",
            "sortByColumn": "WeekdayID",
            "sourceColumn": "WeekdayShortNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "DayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "'Dim Date'[WeekdayShortNameDE] & \" \" & FORMAT('Dim Date'[DateBK], \"dd.mm.yy\")",
            "isDataTypeInferred": true,
            "lineageTag": "65b548df-1589-47a1-9566-94eafceba7eb",
            "sortByColumn": "DateBK",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Dim Date'[DateBK], \"mm.yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "38a2ec2d-dfe2-4fb0-9a7f-d5d19e6d1737",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WeekID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(WEEKNUM('Dim Date'[DateBK],21),  \"00\")",
            "isDataTypeInferred": true,
            "lineageTag": "f7f873b1-0ed9-4679-9837-2833edbd7e74",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WeekNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"KW \" & 'Dim Date'[WeekID]",
            "isDataTypeInferred": true,
            "lineageTag": "c5f39ac5-f253-4920-a6f4-2be5be060ca2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "JiraSprintID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74de0189-0e91-4be2-b5e5-dcb888f86728",
            "sourceColumn": "JiraSprintID",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "beb1db79-327f-4113-b85d-13704e2037c1",
        "partitions": [
          {
            "name": "Dim Date-7c7e4c46-d240-452e-8230-73c8bf8f5d72",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimDate,",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([YearID] <> 2025 and [YearID] <> 2026 and [YearID] <> 2027 and [YearID] <> 2028 and [YearID] <> 2029 and [YearID] <> 2030))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Sprint",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "JiraSprintID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2dc62a27-5dfc-4bad-8f08-d24ed347f190",
            "sourceColumn": "JiraSprintID",
            "summarizeBy": "none"
          },
          {
            "name": "SprintName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fe3f721-9ab4-4a1b-b061-3f0b5cc3ffcb",
            "sortByColumn": "JiraSprintID",
            "sourceColumn": "SprintName",
            "summarizeBy": "none"
          },
          {
            "name": "SprintNameShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7d88e82-9a43-4425-8726-a77cda2a0886",
            "sourceColumn": "SprintNameShort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2dacb36a-5df0-4fbf-a289-1eba7f2a8947",
        "partitions": [
          {
            "name": "Dim Sprint-4bb76aa4-d47d-4ed1-a752-2c8eff41cb9e",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimSprint",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim User",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fdcae43b-f200-4761-a34c-6b42ba30fa1a",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "UserInitials",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "671e4ced-5637-4f11-83de-d902ae28baeb",
            "sourceColumn": "UserInitials",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "599c4bcf-afa4-4286-a390-46d4aa49bbef",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "UserName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c1e014a-da23-4968-ba5e-1290c4949e5d",
            "sortByColumn": "BlueAntUserSortId",
            "sourceColumn": "UserName",
            "summarizeBy": "none"
          },
          {
            "name": "UserEmail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d8ee3fdd-3f1e-4801-968d-4e6caf19c849",
            "sourceColumn": "UserEmail",
            "summarizeBy": "none"
          },
          {
            "name": "TeamName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f991cda-5270-46e5-a86c-64449ebb69da",
            "sortByColumn": "TeamNameSortId",
            "sourceColumn": "TeamName",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57dc1637-7ba9-44ff-8dae-eaa4513ae871",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "TeamGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bd33057-fc12-4d7e-ad6e-fa9c842a7d7c",
            "sortByColumn": "TeamGroupSortId",
            "sourceColumn": "TeamGroup",
            "summarizeBy": "none"
          },
          {
            "name": "TeamNameSortId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "66c281f8-f8cd-4c98-8176-8f76409e9c22",
            "sourceColumn": "TeamNameSortId",
            "summarizeBy": "none"
          },
          {
            "name": "TeamGroupSortId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08eda58a-0322-45b7-8cd1-84c5400150a1",
            "sourceColumn": "TeamGroupSortId",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntUserSortId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a32a79f2-0668-450f-94e0-537e60a69593",
            "sourceColumn": "BlueAntUserSortId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "162bb363-9a3d-4d2f-8d29-758549a95409",
        "partitions": [
          {
            "name": "Dim User-1333c04f-f59d-4bd9-b35a-7c38ea29f7c3",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimUser,",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([UserID] <> 49))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "8e93c620-539a-4349-bb12-68312b1eac38",
        "measures": [
          {
            "name": "AC",
            "displayFolder": "Blue Ant",
            "expression": "SUM('Fact Worklog'[BlueAntTimeMinutes]) / 60 / 8",
            "formatString": "#,0.00",
            "lineageTag": "4e916f0a-658a-46bc-a8ca-a66d0020692a"
          },
          {
            "name": "AC (internal)",
            "displayFolder": "Blue Ant",
            "expression": "CALCULATE([AC], 'Fact Worklog'[Billable] = FALSE())",
            "formatString": "#,0.00",
            "lineageTag": "2762c60b-ff78-44b1-89af-a412460d42ce"
          },
          {
            "name": "AC (external)",
            "displayFolder": "Blue Ant",
            "expression": "CALCULATE([AC], 'Fact Worklog'[Billable] = TRUE())",
            "formatString": "#,0.00",
            "lineageTag": "1844ce38-863b-47a8-a641-f13d26dcd6af"
          },
          {
            "name": "Absence",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Blue Ant",
            "expression": "Count('Dim Absence'[DateID])",
            "formatString": "#,0",
            "lineageTag": "84f9709b-3a9e-4ec3-9a42-ade754a813c0"
          },
          {
            "name": "PL (Jira)",
            "displayFolder": "Jira",
            "expression": "SUM('Fact Jira Issue'[OriginalTimeEstimate]) / 60 / 8",
            "formatString": "#,0.00",
            "lineageTag": "cd84d502-6e46-4265-836a-4e1ef9fc1750"
          },
          {
            "name": "Daily rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Blue Ant",
            "expression": "AVERAGE('Dim Project Role'[ExternalCostPerHour]) * 8",
            "lineageTag": "3182be51-f0b5-4493-a1b6-49e63a8b0153"
          },
          {
            "name": "Budget",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _sum = SUM('Dim Project'[ProjectBudget])",
              "RETURN",
              "    IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_sum)"
            ],
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "37dc163c-50a9-4d53-ae8c-69f973ff53b1"
          },
          {
            "name": "Capacity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Blue Ant",
            "expression": [
              "",
              "    VAR _sum = SUM('Fact Capacity'[WorktimeHours]) / 8",
              "RETURN",
              "      IF(ISINSCOPE('Dim Project'[ProjectName]),BLANK(),",
              "        IF(ISINSCOPE('Dim Deal'[DealName]),BLANK(),_sum))  "
            ],
            "lineageTag": "9d3e0188-d190-43a6-9d2a-3320b291339e"
          },
          {
            "name": "Utilization AC (external)",
            "displayFolder": "Blue Ant",
            "expression": "DIVIDE([AC (external)], [Capacity])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "b5b72a87-7653-41a4-bb2b-3df0243bba38"
          },
          {
            "name": "Absence NM4",
            "displayFolder": "Blue Ant\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Absence],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "e90ff906-5cc9-4d6c-ae0b-e585b119acb9"
          },
          {
            "name": "Capacity NM4",
            "displayFolder": "Blue Ant\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Capacity],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "667116de-2216-4c48-a612-31faa34eaeb0"
          },
          {
            "name": "AC (external) LM6NM6",
            "displayFolder": "Blue Ant\\_Next Last 6 Months",
            "expression": [
              "",
              "VAR _MaxDate = CALCULATE(MIN('Dim Date'[DateBK]), DATEADD('Dim Date'[DateBK], 6, MONTH))",
              "VAR _Result =",
              "    CALCULATE (",
              "        [AC (external)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "216a085c-8079-41c1-8355-850c6b1061d7"
          },
          {
            "name": "Utilization AC (external) YTD",
            "displayFolder": "Blue Ant",
            "expression": "TOTALYTD([Utilization AC (external)], 'Dim Date'[DateBK])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "843ef2d2-580e-486a-9264-835df5c72181"
          },
          {
            "name": "Utilization AC (external) YTD Visual",
            "displayFolder": "Blue Ant",
            "expression": "TOTALYTD([Utilization AC (external)], 'Dim Date Visualiation'[DateBK])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "56f743f3-1c11-483d-8c3d-dedf65ee7221"
          },
          {
            "name": "PL remaining (Jira)",
            "displayFolder": "Jira",
            "expression": [
              "",
              "    VAR _sum = SUM('Fact Jira Issue'[CurrentTimeEstimate]) / 60 / 8",
              "RETURN",
              "    _sum"
            ],
            "formatString": "#,0.00",
            "lineageTag": "2d45df75-2c8f-4f9a-afc9-bd30376d2cc2"
          },
          {
            "name": "AC (Jira)",
            "displayFolder": "Jira",
            "expression": "SUM('Fact Worklog'[JiraTimeSpentMinutes]) / 60 / 8",
            "formatString": "#,0.00",
            "lineageTag": "3223e246-9d6c-472d-9b9b-073430e254e2"
          },
          {
            "name": "Invoice",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _sum = SUM('Fact Invoice'[InvoiceAmount])",
              "RETURN",
              "      IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_sum)"
            ],
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "abc0e6ff-615c-4a80-8d12-d4d948beb7a9"
          },
          {
            "name": "Budget remaining",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              " IF( ISBLANK([Budget]), BLANK(), [Budget] - [Invoice kum])"
            ],
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "36cad81e-a702-4ba5-a669-77616dcb6a99"
          },
          {
            "name": "Budget days",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _cal = SUM('Dim Project Task'[WorkPlannedHours]) / 8",
              "RETURN",
              "     IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_cal)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "52cd3586-5ad4-4680-b138-41a6996397c5"
          },
          {
            "name": "Budget days remaining",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _cal = IF( ISBLANK([Budget days]), BLANK(), [Budget days] - [AC (external) kum])",
              "RETURN",
              "    IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_cal)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "1214b4d4-ed22-43dd-99e4-eee8676a3859"
          },
          {
            "name": "Invoice AC (external)",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _sum = SUM('Fact Invoice'[WorktimeAccountableMinutes]) / 60 / 8",
              "RETURN",
              "      IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_sum)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "aa79f0f0-91d3-485b-a4ae-c7d609dc12ac"
          },
          {
            "name": "Invoice AC (internal)",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "SUM('Fact Invoice'[WorktimeNotAccountableMinutes]) / 60 / 8",
            "formatString": "#,0.00",
            "lineageTag": "846e1f16-c75f-437c-b7b4-985301d995d4"
          },
          {
            "name": "Invoice AC",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "[Invoice AC (external)] + [Invoice AC (internal)]",
            "formatString": "#,0.00",
            "lineageTag": "41757278-a616-4b21-878e-52c4a8842c72"
          },
          {
            "name": "Working days",
            "displayFolder": "Date",
            "expression": [
              "",
              "    VAR _year = SELECTEDVALUE('Dim Date'[YearID])",
              "RETURN    ",
              "    CALCULATE(COUNT('Fact Capacity'[WorktimeHours]), FILTER(ALL('Dim Date'), 'Dim Date'[YearID] = _year))"
            ],
            "formatString": "0",
            "lineageTag": "4a3e3d6d-50e4-41df-a145-f5ebb0ebe9c1"
          },
          {
            "name": "Target",
            "displayFolder": "Target",
            "expression": "SUM('Fact Capacity'[TargetHours]) / 8",
            "formatString": "#,0.00000",
            "lineageTag": "9ca8ff76-cd99-49c9-97dd-7a20fa666ff7"
          },
          {
            "name": "Working days actual",
            "displayFolder": "Date",
            "expression": [
              "",
              "    VAR _year = SELECTEDVALUE('Dim Date'[YearID])",
              "RETURN    ",
              "    CALCULATE(COUNT('Fact Capacity'[WorktimeHours]), 'Dim Date'[DateBK] < TODAY(), 'Dim Date'[YearID] = _year)"
            ],
            "formatString": "#,0",
            "lineageTag": "19b80d7d-3b84-4f11-9c34-008d7013f2d9"
          },
          {
            "name": "Target actual",
            "displayFolder": "Target",
            "expression": "CALCULATE([Target], FILTER('Dim Date', 'Dim Date'[DateBK] <= TODAY()))",
            "formatString": "#,0.00",
            "lineageTag": "26e21033-9c06-425c-9363-6e1c9f32f5e8"
          },
          {
            "name": "Daily rate Invoice",
            "displayFolder": "Blue Ant",
            "expression": "DIVIDE([Invoice kum], [Invoice AC total])",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "dbda225a-36bf-40a3-be54-d462a0c67412"
          },
          {
            "name": "Budget Rate",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "DIVIDE([Invoice kum] + [Invoice open], [Budget])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "8de17349-8e1f-486e-814b-8530d73db1a2"
          },
          {
            "name": "AC Delta",
            "displayFolder": "Blue Ant",
            "expression": "[AC] - [AC (Jira)]",
            "formatString": "#,0.00",
            "lineageTag": "6d5f856c-3c94-4201-b0aa-cc5803e73e19"
          },
          {
            "name": "Project acvtive",
            "displayFolder": "Date",
            "expression": [
              "",
              "    VAR _maxdate = MAX('Dim Date'[DateID])",
              "    VAR _mindate = MIN('Dim Date'[DateID])",
              "RETURN",
              "    IF(SELECTEDVALUE('Dim Project'[StartDateID]) < _maxdate && SELECTEDVALUE('Dim Project'[EndDateID]) > _mindate, 1 , BLANK())"
            ],
            "formatString": "0",
            "lineageTag": "6b3bfae1-8639-4931-a38d-c309b2e8aa7b"
          },
          {
            "name": "Invoice kum",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "CALCULATE([Invoice], FILTER(ALL('Dim Date'[DateBK]), 'Dim Date'[DateBK] <= MAX('Dim Date'[DateBK])))",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "5ea95364-6802-4407-89d0-e56da2486cdd"
          },
          {
            "name": "AC (external) YTD",
            "displayFolder": "Blue Ant",
            "expression": "TOTALYTD([AC (external)], 'Dim Date'[DateBK])",
            "formatString": "#,0.00",
            "lineageTag": "e945adb7-c5d1-4abd-be93-48cab12c1228"
          },
          {
            "name": "Invoice AC total",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "CALCULATE([Invoice AC], ALL('Dim Date'))",
            "formatString": "#,0.00",
            "lineageTag": "4a9434f9-9172-4b88-b0d6-1cb5d82c211d"
          },
          {
            "name": "Budget days rate",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "DIVIDE([AC (external) kum], [Budget days])"
            ],
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "5d0dce93-81f0-4e84-9a94-062f133de095"
          },
          {
            "name": "Plannable",
            "displayFolder": "Jira",
            "expression": "[Capacity] - [PL (Jira)]",
            "formatString": "#,0.00",
            "lineageTag": "876ebc08-50ad-43ca-8e14-e31ee2bd7814"
          },
          {
            "name": "AC (external) NM4",
            "displayFolder": "Blue Ant\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [AC (external)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "c8e807bb-e736-4651-8594-52b3830789ea"
          },
          {
            "name": "Capacity remaining",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Blue Ant",
            "expression": [
              "",
              "    VAR _date = TODAY()",
              "    VAR _mindate = MIN('Dim Date'[DateBK])",
              "    VAR _maxdate = MAX('Dim Date'[DateID])",
              "RETURN",
              "    IF( ",
              "        _date < _mindate,  ",
              "        CALCULATE([Capacity], 'Dim Date'[DateBK] >= _mindate, 'Dim Date'[DateID] <= _maxdate),",
              "        CALCULATE([Capacity], 'Dim Date'[DateBK] >= _date, 'Dim Date'[DateID] <= _maxdate)",
              "    )    "
            ],
            "lineageTag": "dabdfbc4-09e0-4b35-b1ff-a50ac8df60d2"
          },
          {
            "name": "Delta (Capacity remaining, PL remaining (Jira))",
            "displayFolder": "Jira",
            "expression": "[Capacity remaining] - [PL remaining (Jira)]",
            "formatString": "#,0.00",
            "lineageTag": "6d0fc72c-f30c-403c-8526-91f7b0f0ecbd"
          },
          {
            "name": "AC (external) LM4",
            "displayFolder": "Blue Ant\\_Last 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MAX ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [AC (external)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "9e5b40fc-8929-4ec9-b522-6ecd71457d21"
          },
          {
            "name": "DELTA (AC (external), PL all TM1 (bill)) LM4",
            "displayFolder": "Blue Ant\\_Last 4 Months",
            "expression": "[PL all TM1 (bill) LM4] - [AC (external) LM4]",
            "formatString": "#,0.00",
            "lineageTag": "e5d2e325-c349-4dd6-942a-39a9d1a7b823"
          },
          {
            "name": "AC (external) PY",
            "displayFolder": "Blue Ant",
            "expression": "CALCULATE([AC (external)], SAMEPERIODLASTYEAR('Dim Date'[DateBK]))",
            "formatString": "#,0.00",
            "lineageTag": "b6c9f974-f729-48ff-b8b6-b40f8a4a381a"
          },
          {
            "name": "AC (external) kum",
            "displayFolder": "Blue Ant",
            "expression": "CALCULATE([AC (external)], FILTER(ALL('Dim Date'[DateBK]), 'Dim Date'[DateBK] <= MAX('Dim Date'[DateBK])))",
            "formatString": "#,0.00",
            "lineageTag": "99f84863-f390-409d-865b-85abb3c95135"
          },
          {
            "name": "Invoice YTD",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "TOTALYTD([Invoice], 'Dim Date'[DateBK])",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "786cec3e-2519-4432-ad0e-e8aa2f2bb348"
          },
          {
            "name": " Target (AC-Target)",
            "displayFolder": "Target",
            "expression": "[AC (external)] -[Target]",
            "formatString": "#,0.00",
            "lineageTag": "e61b8abb-b373-4760-a92f-8787be311f03"
          },
          {
            "name": " Target (AC-actual)",
            "displayFolder": "Target",
            "expression": "[AC (external)] - [Target actual]",
            "formatString": "#,0.00",
            "lineageTag": "4a08fc4f-4f25-437c-9671-39c6da0175ce"
          },
          {
            "name": "AC (h)",
            "displayFolder": "Blue Ant",
            "expression": "SUM('Fact Worklog'[BlueAntTimeMinutes]) / 60 ",
            "formatString": "#,0.00",
            "lineageTag": "6cbcc9f3-5db9-45a2-87e8-7384a85b0416"
          },
          {
            "name": "AC (Jira) h",
            "displayFolder": "Blue Ant",
            "expression": "SUM('Fact Worklog'[JiraTimeSpentMinutes]) / 60 ",
            "formatString": "#,0.00",
            "lineageTag": "53013f76-22ca-499e-abfc-4f91df85103c"
          },
          {
            "name": "AC Delta h",
            "displayFolder": "Blue Ant",
            "expression": "[AC (h)] - [AC (Jira) h]",
            "formatString": "#,0.00",
            "lineageTag": "38b78bcc-378b-46d2-976e-cbc97a6e8d4d"
          },
          {
            "name": "Target actual (User)",
            "displayFolder": "User\\Target",
            "expression": "CALCULATE([Target], FILTER('Dim Date', 'Dim Date'[DateBK] <= TODAY()), FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "74337561-04d1-47f7-80d2-c5df0f2ce86d"
          },
          {
            "name": "Target (User)",
            "displayFolder": "User\\Target",
            "expression": "CALCULATE([Target], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "16b1016a-de10-4e96-8e5e-059de69668ad"
          },
          {
            "name": "AC (external) (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([AC (external)], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "0b783d51-d217-40c4-b09a-3f33b2fef919"
          },
          {
            "name": " Target (AC-actual) (user)",
            "displayFolder": "User\\Target",
            "expression": "[AC (external) (User)] - [Target actual (User)]",
            "formatString": "#,0.00",
            "lineageTag": "9f1817b4-fe15-417b-a120-4c2a7706c66a"
          },
          {
            "name": " Target (AC-Target) (user)",
            "displayFolder": "User\\Target",
            "expression": "[AC (external) (User)] - [Target (User)]",
            "formatString": "#,0.00",
            "lineageTag": "eed3f862-e5ba-41e6-81c6-d49e338ad88e"
          },
          {
            "name": "AC (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([AC], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "5253b260-7baa-4f0b-a3ca-ae0f79e73e49"
          },
          {
            "name": "AC (internal) (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([AC (internal)], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "b7e39c58-65af-4756-b189-9ebed0885afc"
          },
          {
            "name": "Budget days (months)",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _cal = SUM('Dim Project Task'[WorkPlannedHours]) / 8",
              "    VAR _mindate = MIN('Dim Date'[DateID])",
              "    VAR _maxdate = MAX('Dim Date'[DateID])",
              "    VAR _start = SELECTEDVALUE('Dim Project'[StartDateID])",
              "    VAR _end = SELECTEDVALUE('Dim Project'[EndDateID])",
              "RETURN",
              "    IF(_start <= _maxdate && _end >= _mindate,",
              "     IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_cal),",
              "         BLANK())"
            ],
            "formatString": "#,0.00",
            "lineageTag": "59e1231b-5ca2-4446-a4c0-f37bff859ca0"
          },
          {
            "name": "Budget days remaining (months)",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _cal = IF( ISBLANK([Budget days (months)]), BLANK(), [Budget days (months)] - [AC (external) kum])",
              "RETURN",
              "    IF(ISINSCOPE('Dim User'[UserName]),BLANK(),_cal)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3777353c-a853-4c30-8130-899d53eda849"
          },
          {
            "name": "Page Info Projects",
            "displayFolder": "_PageInfos",
            "expression": [
              "",
              "",
              "    VAR _ConCatProject = CALCULATE( CONCATENATEX( VALUES( 'Dim Project'[ProjectName]),  'Dim Project'[ProjectName], \", \"))",
              "                           ",
              "RETURN",
              " _ConCatProject"
            ],
            "lineageTag": "c5915d6e-0aee-4cd6-b8e3-99fe4c65e0b0"
          },
          {
            "name": "Page Info Date",
            "displayFolder": "_PageInfos",
            "expression": [
              "",
              "        VAR _minId = MIN('Dim Date'[DateID])",
              "        VAR _maxId = MAX('Dim Date'[DateID])",
              "        VAR _min = LOOKUPVALUE('Dim Date'[MonthShortNameDE],'Dim Date'[DateID], _minId)",
              "        VAR _max = LOOKUPVALUE('Dim Date'[MonthShortNameDE],'Dim Date'[DateID], _maxId)",
              "        VAR _minYear = MIN('Dim Date'[YearID])",
              "        VAR _maxYear = MAX('Dim Date'[YearID])",
              "",
              "        VAR _Date =",
              "        IF (",
              "                        _min = _max && _minYear = _maxYear,",
              "                        _min & \" \" & _minYear,",
              "                            IF(",
              "                                    _minId < _maxId && _minYear = _maxYear,",
              "                                    _min & \" - \" & _max & \" \" & _maxYear,",
              "                                    _min & \" \" & _minYear &\" - \" & _max & \" \" & _maxYear",
              "                                    ",
              "                                )",
              "            )   ",
              "   RETURN",
              "            _Date"
            ],
            "lineageTag": "125bf237-5143-45c1-80db-4d6ac976d653"
          },
          {
            "name": "MaxDate",
            "displayFolder": "Date",
            "expression": [
              "",
              "    VAR _max = MAX('Fact Worklog'[DateID])",
              "    VAR _date = LOOKUPVALUE('Dim Date'[DateBK], 'Dim Date'[DateID], _max)",
              "RETURN ",
              "    _date"
            ],
            "formatString": "Short Date",
            "lineageTag": "5e2a31c3-1f23-4b8f-8eec-ac11cf313102"
          },
          {
            "name": "PL all TM1 (User)",
            "displayFolder": "User\\Plan",
            "expression": "CALCULATE([PL all TM1], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "18987825-3be8-413e-a1db-4ddf84e3eb55"
          },
          {
            "name": "Absence (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([Absence], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0",
            "lineageTag": "56047c75-cd0d-4929-87a2-035a33d3aaba"
          },
          {
            "name": "Capacity (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([Capacity], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "732000eb-af4e-445e-b5fc-99ab40a8ec1b"
          },
          {
            "name": "Capacity remaining (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([Capacity remaining], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "ba5094c4-7af3-4f21-b189-2e2ec670383a"
          },
          {
            "name": "PL (User) NM4",
            "displayFolder": "User\\Plan",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "a3d214e7-859f-4fbf-b312-1de44bc7e537"
          },
          {
            "name": "AC (h) User",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE(SUM('Fact Worklog'[BlueAntTimeMinutes]) / 60, FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "635703a3-0db2-4603-af01-ff7635d806ac"
          },
          {
            "name": "AC (h) User Jira",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE(SUM('Fact Worklog'[JiraTimeSpentMinutes]) / 60 , FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "13d7a588-267c-4137-a4d7-68d13ee59c29"
          },
          {
            "name": "AC (h) User Delta",
            "displayFolder": "User\\Blue Ant",
            "expression": "[AC (h) User] - [AC (h) User Jira]",
            "formatString": "#,0.00",
            "lineageTag": "2bb99eac-57ab-4e6b-a6cd-0333e6303239"
          },
          {
            "name": "Utilization AC (external) User",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "User\\Blue Ant",
            "expression": "DIVIDE([AC (external) (User)], [Capacity (User)])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "e764629c-9bd0-40de-9bff-95935e88943e"
          },
          {
            "name": "PL TM1",
            "displayFolder": "Plan",
            "expression": "CALCULATE(SUM('Fact Plan'[PlannedWorkPerDay]), 'Fact Plan'[PlanningType] = 0 )",
            "formatString": "#,0.00",
            "lineageTag": "836f9ed7-72b1-4365-8d0f-4c3125f2c4c1"
          },
          {
            "name": "PL all TM1 LM4",
            "displayFolder": "Plan\\_Last 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MAX ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.0000",
            "lineageTag": "8d5ea6e3-142a-40d8-b7b4-13943081c968"
          },
          {
            "name": "Utilization (PL TM1)",
            "displayFolder": "Plan",
            "expression": "DIVIDE([PL all TM1], [Capacity])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "dd4a8d92-a9d2-4b72-a267-2a34fb03c820"
          },
          {
            "name": "Utilization (PL TM1) YTD",
            "displayFolder": "Plan",
            "expression": "TOTALYTD([Utilization (PL TM1)], 'Dim Date'[DateBK])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "1762d396-35a9-465d-876c-eedd57ef3662"
          },
          {
            "name": "Utilization (PL TM1) YTD Visual",
            "displayFolder": "Plan",
            "expression": "TOTALYTD([Utilization (PL TM1)], 'Dim Date Visualiation'[DateBK])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "9af7251b-155a-4d5a-aa40-42795d47d504"
          },
          {
            "name": "Utilization (PL TM1) LM4",
            "displayFolder": "Plan\\_Last 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MAX ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Utilization (PL TM1)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "1a84aa99-212e-4da8-a469-0331c19b7b6b"
          },
          {
            "name": "Budget-PL TM1 NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": "[Budget days remaining] - [PL all TM1 NM4]",
            "formatString": "#,0.00",
            "lineageTag": "00fc6db2-0f36-4509-b3a7-c44d88d22ad1"
          },
          {
            "name": "Utilization (PL TM1) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Utilization (PL TM1)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "06ee0aaf-d225-43c8-af26-45b80cac9c6e"
          },
          {
            "name": "PL all TM1 LM6NM6",
            "displayFolder": "Plan\\_Next Last 6 Months",
            "expression": [
              "",
              "VAR _MaxDate = CALCULATE(MIN('Dim Date'[DateBK]), DATEADD('Dim Date'[DateBK], 6, MONTH))",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "   _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "c54c3e06-e6d7-4d17-ab16-e8575087c9e3"
          },
          {
            "name": "PL TM1 (nobill)",
            "displayFolder": "Plan",
            "expression": "CALCULATE([PL TM1], 'Fact Plan'[Billable] = 0 )",
            "formatString": "#,0.00",
            "lineageTag": "bbc1217a-75c8-4c80-9895-2f081a8ce9f4"
          },
          {
            "name": "PL TM1 (bill)",
            "displayFolder": "Plan",
            "expression": "CALCULATE([PL TM1], 'Fact Plan'[Billable] = 1 )",
            "formatString": "#,0.00",
            "lineageTag": "90b65ad1-e764-4861-9025-08f55ac2f312"
          },
          {
            "name": "RES TM1",
            "displayFolder": "Plan",
            "expression": "CALCULATE(SUM('Fact Plan'[PlannedWorkPerDay]), 'Fact Plan'[PlanningType] = 1)",
            "formatString": "#,0.00",
            "lineageTag": "40aa1cde-9127-4e09-86c9-02ba354d6cc0"
          },
          {
            "name": "RES TM1 (bill)",
            "displayFolder": "Plan",
            "expression": "CALCULATE([RES TM1], 'Fact Plan'[Billable] = 1)",
            "formatString": "#,0.00",
            "lineageTag": "8aed3fff-f6cc-468a-b7c6-58033747dbd6"
          },
          {
            "name": "RES TM1 (nobill)",
            "displayFolder": "Plan",
            "expression": "CALCULATE([RES TM1], 'Fact Plan'[Billable] = 0)",
            "formatString": "#,0.00",
            "lineageTag": "9e495fde-5237-442c-b80e-908c0008ccb8"
          },
          {
            "name": "PL TM1 (bill) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL TM1 (bill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "a16afd3b-b790-4c49-a0cd-fc2e2d70fdb3"
          },
          {
            "name": "PL TM1 (nobill) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL TM1 (nobill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "6edaad13-a991-47e9-bfc7-07a9bbfbce8a"
          },
          {
            "name": "RES TM1 (bill) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [RES TM1 (bill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "9cfac6b1-b1ab-431d-9572-33bb84002af9"
          },
          {
            "name": "RES TM1 (nobill) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [RES TM1 (nobill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3b0bfe5a-4b89-471a-aae3-09de33b3e997"
          },
          {
            "name": "PL all TM1",
            "displayFolder": "Plan",
            "expression": "SUM('Fact Plan'[PlannedWorkPerDay])",
            "formatString": "#,0.00",
            "lineageTag": "c4c02bc6-cd81-4535-9b0b-35c2ab2d172a"
          },
          {
            "name": "PL all TM1 NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "603863e7-7c83-4b49-b40b-0b4806a45acf"
          },
          {
            "name": "Capacity - PL all TM1 (bill) NM4",
            "displayFolder": "Blue Ant\\_Next 4 Months",
            "expression": "[Capacity NM4] - [PL all TM1 (bill) NM4]",
            "formatString": "#,0.00",
            "lineageTag": "e8656eb0-9c0e-4a6c-b7a7-3e553c9a589b"
          },
          {
            "name": "Capacity - PL all TM1 NM4",
            "displayFolder": "Blue Ant\\_Next 4 Months",
            "expression": "[Capacity NM4] - [PL all TM1 NM4]",
            "formatString": "#,0.00",
            "lineageTag": "32ae7844-b237-48d5-863a-f00ae5ab69ff"
          },
          {
            "name": "PL all TM1 (bill)",
            "displayFolder": "Plan",
            "expression": "CALCULATE([PL all TM1], 'Fact Plan'[Billable] = 1 )",
            "formatString": "#,0.00",
            "lineageTag": "9dd4ff01-d5a2-4efa-9e41-a0bcf1a38c57"
          },
          {
            "name": "PL all TM1 (nobill)",
            "displayFolder": "Plan",
            "expression": "CALCULATE([PL all TM1], 'Fact Plan'[Billable] = 0)",
            "formatString": "#,0.00",
            "lineageTag": "2c210e8a-d7b0-49af-949b-9973aab4248d"
          },
          {
            "name": "PL all TM1 (bill) LM6NM6",
            "displayFolder": "Plan\\_Next Last 6 Months",
            "expression": [
              "",
              "VAR _MaxDate = CALCULATE(MIN('Dim Date'[DateBK]), DATEADD('Dim Date'[DateBK], 6, MONTH))",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1 (bill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "   _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "fb38bfdc-391c-43a2-93cb-6ce782581acd"
          },
          {
            "name": "PL all TM1 (bill) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1 (bill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3b491bf4-c989-437f-904f-38216b90b44d"
          },
          {
            "name": "PL all TM1 (nobill) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1 (nobill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "5593fa62-470b-455d-9f32-231d9d70b49c"
          },
          {
            "name": "Target LM6NM6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Target\\_Next Last 6 Months",
            "expression": [
              "",
              "VAR _MaxDate = CALCULATE(MIN('Dim Date'[DateBK]), DATEADD('Dim Date'[DateBK], 6, MONTH))",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Target],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "   _Result"
            ],
            "lineageTag": "f4cff89c-2b69-49b9-9bbb-e36ba2ec4631"
          },
          {
            "name": "PL all TM1 (bill) User",
            "displayFolder": "User\\Plan",
            "expression": "CALCULATE([PL all TM1 (bill)], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "f29e5d81-9c93-4ee5-9033-e4656d97ebba"
          },
          {
            "name": "PL all TM1 (nobill) User",
            "displayFolder": "User\\Plan",
            "expression": "CALCULATE([PL all TM1 (nobill)], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00",
            "lineageTag": "745d504b-c160-4a4f-be68-2df3543ba5b8"
          },
          {
            "name": "AC LM4",
            "displayFolder": "Blue Ant\\_Last 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MAX ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [AC],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "5f9b41d9-e213-4f23-bca4-5af94f5ffb02"
          },
          {
            "name": "AC LM6NM6",
            "displayFolder": "Blue Ant\\_Next Last 6 Months",
            "expression": [
              "",
              "VAR _MaxDate = CALCULATE(MIN('Dim Date'[DateBK]), DATEADD('Dim Date'[DateBK], 6, MONTH))",
              "VAR _Result =",
              "    CALCULATE (",
              "        [AC],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "bc8b3405-c23a-480a-9977-1f90d5a126bc"
          },
          {
            "name": "PL all TM1 (nobill) LM6NM6",
            "displayFolder": "Plan\\_Next Last 6 Months",
            "expression": [
              "",
              "VAR _MaxDate = CALCULATE(MIN('Dim Date'[DateBK]), DATEADD('Dim Date'[DateBK], 6, MONTH))",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1 (nobill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -12,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "   _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3b0d2ca0-dd9a-4265-bf41-c28b0812068b"
          },
          {
            "name": "PL all TM1 (bill) LM4",
            "displayFolder": "Plan\\_Last 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MAX ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1 (bill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "18f12179-2535-4b10-8f03-82dfa03bfd16"
          },
          {
            "name": "PL all TM1 (nobill) LM4",
            "displayFolder": "Plan\\_Last 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MAX ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [PL all TM1 (nobill)],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            -4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00",
            "lineageTag": "b113c608-7c09-4423-b907-20429b45be96"
          },
          {
            "name": "Utilization (PL all TM1 (bill))",
            "displayFolder": "Plan",
            "expression": "DIVIDE([PL all TM1 (bill)], [Capacity])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "71997ea5-a3b4-4244-99f4-2d9f2f99384f"
          },
          {
            "name": "Utilization (PL all TM1 (bill)) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Utilization (PL all TM1 (bill))],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "81d83aa7-26fc-4335-82a1-74cc0d29b596"
          },
          {
            "name": "Utilization (PL all TM1 (bill)) YTD",
            "displayFolder": "Plan",
            "expression": "TOTALYTD([Utilization (PL all TM1 (bill))], 'Dim Date'[DateBK])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "176dcc4d-38a0-45e0-80de-73895985d55c"
          },
          {
            "name": "PL remaining costs (Jira)",
            "displayFolder": "Jira",
            "expression": [
              "",
              "    VAR _sum = SUM('Fact Jira Issue'[CurrentTimeEstimateCost])",
              "RETURN",
              "     _sum    "
            ],
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "3d7f5b21-1f75-4ef7-b0f0-ab0d8f2fe37d"
          },
          {
            "name": "Budget total",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "SUM('Fact Budget'[Wert])",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "2ff60587-5d9b-4bda-959b-d3c3578fb47c"
          },
          {
            "name": "Budget Days total",
            "displayFolder": "Blue Ant\\Budget",
            "expression": "SUM('Fact Budget Days'[Wert])",
            "formatString": "#,0.00",
            "lineageTag": "e8a3e3ec-9787-40e0-8c90-f8be1bf21d5b"
          },
          {
            "name": "PL all TM1 (bill) (Invoice)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Plan",
            "expression": [
              "",
              "    VAR _maxdate = MAX('Fact Invoice'[EndDateID])",
              "RETURN",
              "    CALCULATE( SUM('Fact Plan'[PlannedWorkPerDay]), 'Fact Plan'[DateID] > _maxdate)"
            ],
            "lineageTag": "5f90ddd5-1998-4596-a940-36f170e6addc"
          },
          {
            "name": "AC Costs",
            "displayFolder": "Blue Ant",
            "expression": "CALCULATE(SUM('Fact Worklog'[CostWorkhours]), 'Fact Worklog'[Billable] = TRUE())",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "aa2a7c45-7f82-49ad-a7ef-95edd9ace6fc"
          },
          {
            "name": "AC (Invoice)",
            "displayFolder": "Blue Ant",
            "expression": [
              "",
              "    VAR _maxdate = MAX('Fact Invoice'[EndDateID])",
              "RETURN",
              "    CALCULATE( [AC (external)], 'Fact Worklog'[DateID] > _maxdate)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "51476364-2fb6-476c-a2a6-92556ecc0b6f"
          },
          {
            "name": "Invoice open",
            "displayFolder": "Blue Ant\\Budget",
            "expression": [
              "",
              "    VAR _allinv = SUM('Fact Worklog'[CostWorkhours])",
              "RETURN",
              "    _allinv - [Invoice kum]"
            ],
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "866aa89f-819a-4dac-b61c-e3084db4b1a6"
          },
          {
            "name": "PL Costs",
            "displayFolder": "Plan",
            "expression": "SUM('Fact Plan'[PlannedCostWorkDays])",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "f7e36ce8-6c99-460c-a11d-38bfa99bf08c"
          },
          {
            "name": "PL Costs (User)",
            "displayFolder": "User\\Plan",
            "expression": "CALCULATE([PL Costs], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "0fcc5b57-de7e-4442-9711-29093724188c"
          },
          {
            "name": "AC Costs (User)",
            "displayFolder": "User\\Blue Ant",
            "expression": "CALCULATE([AC Costs], FILTER('Dim User', 'Dim User'[UserEmail] = USERPRINCIPALNAME()))",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "lineageTag": "a83f691e-be86-4247-80d0-34190657ba1f"
          },
          {
            "name": "Utilization (PL TM1 (bill))",
            "displayFolder": "Plan",
            "expression": "DIVIDE([PL TM1 (bill)], [Capacity])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "0bef08b1-0e05-4aa1-9911-739eb9ea0661"
          },
          {
            "name": "Utilization (PL TM1 (bill)) NM4",
            "displayFolder": "Plan\\_Next 4 Months",
            "expression": [
              "",
              "VAR _MaxDate = MIN ( 'Dim Date'[DateBK] )",
              "VAR _Result =",
              "    CALCULATE (",
              "        [Utilization (PL TM1 (bill))],",
              "        DATESINPERIOD (",
              "            'Dim Date'[DateBK],",
              "            _MaxDate,",
              "            4,",
              "            MONTH",
              "        )",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "0d1f4cf3-4dc9-4772-b2a8-b471a3c55d21"
          },
          {
            "name": "Utilization Target",
            "displayFolder": "Target",
            "expression": "DIVIDE([Target], [Capacity])",
            "formatString": "#,0.00\\ %;-#,0.00\\ %;#,0.00\\ %",
            "lineageTag": "1f7f8bda-a92d-41ca-b6ba-4435f2aa9bdf"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-7670ad20-8ac8-4657-a03a-470c58f42623",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [tmp = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"tmp\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"tmp\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BlueAntCustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8803366d-eb46-48d3-ad20-da96d2cb21f6",
            "sourceColumn": "BlueAntCustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e17de0d6-9bd3-4744-92a6-7d043a3db8f4",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerNameShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de21ad44-f906-486f-8b50-75b5a8db51cc",
            "sourceColumn": "CustomerNameShort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "24f0f631-fbe5-4f76-b4a8-0da67891c494",
        "partitions": [
          {
            "name": "Dim Customer-9902a22c-3287-4489-b216-8d492f56e838",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimCustomer",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Project",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b3d8cc90-2ac4-45b4-bef2-483fe8f46dac",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e645cdfc-2b30-4564-8351-295743ed4a32",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a97eb17e-5755-4935-b683-d39d75a3eee7",
            "sourceColumn": "ProjectName",
            "summarizeBy": "none"
          },
          {
            "name": "StartDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "faa76c0b-63a2-41e0-8c74-70323164205b",
            "sourceColumn": "StartDateID",
            "summarizeBy": "none"
          },
          {
            "name": "EndDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0c1f91f6-957e-419d-a4dd-bce09248f426",
            "sourceColumn": "EndDateID",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectStateName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96d686ad-ab8d-46b1-a611-fc0a02756d5b",
            "sourceColumn": "ProjectStateName",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectBudget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "0d45e742-6a36-4b75-8262-cbcd37146321",
            "sourceColumn": "ProjectBudget",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectManager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f48ee1e-f2ce-4760-95a5-82f78082164a",
            "sourceColumn": "ProjectManager",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectManagerTeamName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2a34108-d329-49d6-bd27-95d526ed2f3d",
            "sourceColumn": "ProjectManagerTeamName",
            "summarizeBy": "none"
          },
          {
            "name": "PL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[PL all TM1]",
            "isDataTypeInferred": true,
            "lineageTag": "03edc0b4-cd2d-4e51-bdda-381ee119aecb",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d29435cb-2a21-49b0-b8d8-7959dc1d249a",
        "partitions": [
          {
            "name": "Dim Project-f7a493f9-6894-4f7a-873c-a1f3c3dbf050",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimProject",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Jira Issue",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "JiraIssueID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "dde9108d-fe6a-409a-818c-3bf86b58fe86",
            "sourceColumn": "JiraIssueID",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalTimeEstimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "77ff19c8-df7e-4fb2-80f4-f04ab59af870",
            "sourceColumn": "OriginalTimeEstimate",
            "summarizeBy": "none"
          },
          {
            "name": "TimeSpent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4d582b18-0108-4d9c-a1f5-a1b8ae5476d9",
            "sourceColumn": "TimeSpent",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentTimeEstimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2fe81400-f7c6-4dc7-b928-153e54eea9a1",
            "sourceColumn": "CurrentTimeEstimate",
            "summarizeBy": "none"
          },
          {
            "name": "HourlyRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "3e4b43d0-956c-46e2-ae28-17b24fd945f5",
            "sourceColumn": "HourlyRate",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalTimeEstimateCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "bdc372c7-5946-4ac6-8cf2-aae0ca112eee",
            "sourceColumn": "OriginalTimeEstimateCost",
            "summarizeBy": "none"
          },
          {
            "name": "TimeSpentCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "b6463935-2a64-4b92-9624-6d6379343e71",
            "sourceColumn": "TimeSpentCost",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentTimeEstimateCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "bf319f05-0a7a-458c-92af-feaa9b6b83e1",
            "sourceColumn": "CurrentTimeEstimateCost",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "1ff29bae-3755-40d3-85c0-73867223637c",
        "partitions": [
          {
            "name": "Fact Jira Issue-d8d9e074-cb89-467f-9981-7b899b02cef0",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactJiraIssue",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Worklog",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "BlueAntTimeMinutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "49c5c52f-dcec-43fa-86b5-79b20a1ce2ef",
            "sourceColumn": "BlueAntTimeMinutes",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "72f1b5d4-5690-4af6-be25-3c275cb8d271",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "JiraTimeSpentMinutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "0898f986-7bf0-4646-9fd6-78a80920791f",
            "sourceColumn": "JiraTimeSpentMinutes",
            "summarizeBy": "none"
          },
          {
            "name": "Billable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "af491560-f766-4fa9-bc84-a849e1ff9361",
            "sourceColumn": "Billable",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08b6240a-be1e-4e48-9a09-f3176edc2ef7",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "IssueID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "953006ac-ee07-4c3f-a6af-9d2431666b96",
            "sourceColumn": "IssueID",
            "summarizeBy": "none"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3f6775bc-fed3-4ed6-b210-985d99c3b9e5",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "WorklogSummary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "59f3eeae-735d-458f-82c8-37f5919a2f78",
            "sourceColumn": "WorklogSummary",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectTaskID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5e934a0-9731-4fa9-86e5-3feec0d6d9ca",
            "sourceColumn": "BlueAntProjectTaskID",
            "summarizeBy": "none"
          },
          {
            "name": "HourlyRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "88230e17-bb7b-4a1c-bbf5-6bc6a20ec760",
            "sourceColumn": "HourlyRate",
            "summarizeBy": "none"
          },
          {
            "name": "CostWorkhours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "7c9a54f0-0ad0-46cb-99c2-b3420179892f",
            "sourceColumn": "CostWorkhours",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "ddcd66ad-9812-45ce-a90a-780977581df8",
        "partitions": [
          {
            "name": "Fact Worklog-eda4b00d-04c1-4109-b910-e1181ec9c2b4",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactWorklog",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Absence",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a2da9c44-2273-48da-ad98-a765498b0772",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24c2bd8b-d9a4-4f56-a423-1c137092ad70",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "AbsenceTypeName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd520a3a-fe6d-473e-8670-e8f362092053",
            "sourceColumn": "AbsenceTypeName",
            "summarizeBy": "none"
          },
          {
            "name": "YearID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c391a3e-67f0-44ca-95a7-2dc870ec0f2f",
            "sourceColumn": "YearID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2522b48d-06a0-425b-b268-db6d228ed8a1",
        "partitions": [
          {
            "name": "Dim Absence-e8570113-ba36-4f46-b394-82127af90601",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimAbsenceType,",
                "    #\"Entfernte Duplikate\" = Table.Distinct(Source, {\"UserID\", \"YearID\", \"DateID\"})",
                "in",
                "    #\"Entfernte Duplikate\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Project Role",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProjectRoleID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a58f5e1f-c14f-4d95-b426-0a5753bce21b",
            "sourceColumn": "ProjectRoleID",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectRoleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5f62d5c-d563-4e18-87b1-21af96b687ea",
            "sourceColumn": "ProjectRoleName",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalCostPerHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "0c12877f-a8f9-4797-80ec-bbd9a78cc508",
            "sourceColumn": "ExternalCostPerHour",
            "summarizeBy": "none"
          },
          {
            "name": "TravelCostPerHour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "163c1373-c9ef-4f49-9d8e-25dd2aa8521d",
            "sourceColumn": "TravelCostPerHour",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c751fa10-6d4b-45c9-bb2a-8be4e8a78e1a",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "63f821d5-96e9-449e-9a94-5aaa099ba231",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "edd20897-4c73-4894-bd3d-f22d94c2baa1",
        "partitions": [
          {
            "name": "Dim Project Role-8d1592fa-00f0-4842-99dc-e095af7afc3c",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimProjectRole",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Capacity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f4510353-4cf9-453d-ae67-4beb0b5aedfc",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5b34eec3-acb1-4f68-8c2c-2c426c917064",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "WorktimeHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "42d07ee8-ecfd-4317-a468-eab9e791ed6b",
            "sourceColumn": "WorktimeHours",
            "summarizeBy": "none"
          },
          {
            "name": "TargetHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e6463fb8-d7ba-4090-9384-b58cc6bdce44",
            "sourceColumn": "TargetHours",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4bea34a8-e6e5-4294-b3b6-1578b0c53e91",
        "partitions": [
          {
            "name": "Fact Capacity-1ec9af21-41d5-40d5-8229-9c162e889133",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactCapacity,",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([UserID] <> -2))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Date Visualiation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe78b917-7da8-46b7-b638-8fefdbdac904",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "DateBK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "31c1f4ff-68b5-4c36-8ccf-5f1337f923cb",
            "sourceColumn": "DateBK",
            "summarizeBy": "none"
          },
          {
            "name": "DayID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74960206-6d70-49e8-9541-592ca4737280",
            "sourceColumn": "DayID",
            "summarizeBy": "none"
          },
          {
            "name": "MonthID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a458aba7-2b99-4f76-a1ef-850d0cba7266",
            "sourceColumn": "MonthID",
            "summarizeBy": "none"
          },
          {
            "name": "YearID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3a7f576-d7a5-4308-9731-a4568e8fa5ec",
            "sourceColumn": "YearID",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d91862e-4568-432e-82c0-eb29f345afad",
            "sortByColumn": "MonthID",
            "sourceColumn": "MonthNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "MonthShortNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c37a4271-163f-4c5a-bfdb-1f1fd2c5146c",
            "sortByColumn": "MonthID",
            "sourceColumn": "MonthShortNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26e2ac85-ba8f-4c6c-9c90-8143ed0371e2",
            "sourceColumn": "WeekdayID",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e4dd7e3-f277-416e-a76d-afd6b60087ed",
            "sortByColumn": "WeekdayID",
            "sourceColumn": "WeekdayNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "WeekdayShortNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a30dbfa-f17d-41a3-bde0-e23e3878de04",
            "sortByColumn": "WeekdayID",
            "sourceColumn": "WeekdayShortNameDE",
            "summarizeBy": "none"
          },
          {
            "name": "DayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "'Dim Date Visualiation'[WeekdayShortNameDE] & \" \" & FORMAT('Dim Date Visualiation'[DateBK], \"dd.mm.\")",
            "isDataTypeInferred": true,
            "lineageTag": "4eca654d-9031-4d56-a786-a001fac33597",
            "sortByColumn": "DayID",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WeekID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(WEEKNUM('Dim Date Visualiation'[DateBK], 21), \"00\")",
            "isDataTypeInferred": true,
            "lineageTag": "5cb32d82-bd9e-47d6-8d09-46a094e9dbef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WeekNameDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"KW \" & 'Dim Date Visualiation'[WeekID]",
            "isDataTypeInferred": true,
            "lineageTag": "4a786204-f51f-4d10-85ed-9d1c7498e789",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "JiraSprintID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a15fd775-c503-42c3-8195-ff1349970566",
            "sourceColumn": "JiraSprintID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "97652fe6-1292-4789-97cf-92b85db1ca7d",
        "partitions": [
          {
            "name": "Dim Date Visualiation-c2c71517-26b8-49dc-b2f9-29e84438e9fd",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimDate",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Invoice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "InvoiceBK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a208d5dd-900d-4ace-9b08-f4cd82e3d649",
            "sourceColumn": "InvoiceBK",
            "summarizeBy": "none"
          },
          {
            "name": "InvoiceNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "163b3e45-bc1e-4a0f-91c3-a2c9e2ca0399",
            "sourceColumn": "InvoiceNumber",
            "summarizeBy": "none"
          },
          {
            "name": "InvoiceDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a633d426-e334-4279-ac64-9cb03e925b5d",
            "sourceColumn": "InvoiceDateID",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntInvoiceStateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a94ac9a1-ddfb-4545-b80d-7cfa321bec21",
            "sourceColumn": "BlueAntInvoiceStateID",
            "summarizeBy": "none"
          },
          {
            "name": "InvoiceAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "1763f2e9-71c5-4237-8201-c3e652610ede",
            "sourceColumn": "InvoiceAmount",
            "summarizeBy": "none"
          },
          {
            "name": "StartDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2e4ad2c-66d9-4aec-aee0-c87bb35388be",
            "sourceColumn": "StartDateID",
            "summarizeBy": "none"
          },
          {
            "name": "EndDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8d1e8247-7500-4e26-834e-cb5d45a8e51c",
            "sourceColumn": "EndDateID",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "10839500-975a-43a8-8c59-67c3ca5460e3",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "WorktimeAccountableMinutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7e1b8e34-dd39-4525-b2b1-9d1db936790f",
            "sourceColumn": "WorktimeAccountableMinutes",
            "summarizeBy": "none"
          },
          {
            "name": "WorktimeNotAccountableMinutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "9959a0ca-7400-4972-bea9-6f85f1ada0c4",
            "sourceColumn": "WorktimeNotAccountableMinutes",
            "summarizeBy": "none"
          },
          {
            "name": "WorktimeTravelMinutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "b254720c-ab33-44f9-b2f5-073c5f30f0a5",
            "sourceColumn": "WorktimeTravelMinutes",
            "summarizeBy": "none"
          },
          {
            "name": "WorktimeTravelNotAccountableMinutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "a1c9cb75-8f96-4e5f-a0ba-b08f00bf28d6",
            "sourceColumn": "WorktimeTravelNotAccountableMinutes",
            "summarizeBy": "none"
          },
          {
            "name": "InvoiceStateName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ddbd382b-2d41-4620-b968-13adf46d1fa0",
            "sourceColumn": "InvoiceStateName",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4ff9b5b2-f873-4adf-927d-69ff81842fe8",
        "partitions": [
          {
            "name": "Fact Invoice-026ea06f-83ad-41d9-b3f1-849d0f55832c",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactInvoice,",
                "    #\"Entfernte Duplikate\" = Table.Distinct(Source, {\"InvoiceBK\"})",
                "in",
                "    #\"Entfernte Duplikate\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Project Task",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BlueAntProjectTaskID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b868f569-f0be-4f82-9d41-3ab61e531549",
            "sourceColumn": "BlueAntProjectTaskID",
            "summarizeBy": "none"
          },
          {
            "name": "TaskName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54b5ac7a-2a49-4b7e-87e4-13e287595e8a",
            "sourceColumn": "TaskName",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectTaskParentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7e54d6f6-04f7-45cf-b5d7-8bf15701da81",
            "sourceColumn": "BlueAntProjectTaskParentID",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "55bd9954-e2d8-4bcb-af6a-ca4c3dd50e84",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "WorkPlannedHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "40df042b-6290-488f-9b78-88263b3df987",
            "sourceColumn": "WorkPlannedHours",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectTaskPath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "PATH('Dim Project Task'[BlueAntProjectTaskID], 'Dim Project Task'[BlueAntProjectTaskParentID])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ad143489-d96d-4dab-bd63-6cafa51eeee6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BlueAntProjectTask L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR _level = PATHITEM('Dim Project Task'[BlueAntProjectTaskPath], 1)",
              "RETURN",
              "    LOOKUPVALUE('Dim Project Task'[TaskName],'Dim Project Task'[BlueAntProjectTaskID], _level)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "61272e25-db0a-4912-b5e7-515073c025ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BlueAntProjectTask L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR _level = PATHITEM('Dim Project Task'[BlueAntProjectTaskPath], 2)",
              "RETURN",
              "    LOOKUPVALUE('Dim Project Task'[TaskName],'Dim Project Task'[BlueAntProjectTaskID], _level)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3250e74d-8fbe-44f0-b6c2-35e103392886",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BlueAntProjectTask L3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR _level = PATHITEM('Dim Project Task'[BlueAntProjectTaskPath], 3)",
              "RETURN",
              "    LOOKUPVALUE('Dim Project Task'[TaskName],'Dim Project Task'[BlueAntProjectTaskID], _level)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e7d8b1bf-4f9c-4c82-987b-025c2a79f590",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "479239c3-a47d-41f0-b65e-1e711393be3b",
        "partitions": [
          {
            "name": "Dim Project Task-2912c271-d41d-48fe-b54b-81754cb112a9",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimProjectTask",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Plan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5a25c39-2567-45d6-99b8-59bb268fd4b3",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9ad199f0-6c2c-44e5-ad55-c9988d0668b0",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "Billable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "000a8fe3-a858-4c14-9fe0-f7da5197d9c5",
            "sourceColumn": "Billable",
            "summarizeBy": "none"
          },
          {
            "name": "PlanningType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9d6f771-446f-43eb-a51f-d51ac311d6fc",
            "sourceColumn": "PlanningType",
            "summarizeBy": "none"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc984d2a-fb6a-4217-9e22-200dd70298aa",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "DealID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ea2d134-cf95-4e68-8102-bfb68d51ad72",
            "sourceColumn": "DealID",
            "summarizeBy": "none"
          },
          {
            "name": "HourlyRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "eee6e98b-947c-4033-8d2d-268c68bbf480",
            "sourceColumn": "HourlyRate",
            "summarizeBy": "none"
          },
          {
            "name": "PlannedWorkPerDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "b2b57ee7-51d2-4ed6-93d3-6ea5d15b4ab9",
            "sourceColumn": "PlannedWorkPerDay",
            "summarizeBy": "sum"
          },
          {
            "name": "PlannedCostWorkDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8264a166-7a46-4033-8ea6-346632f145bc",
            "sourceColumn": "PlannedCostWorkDays",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "507ecb3d-82ad-4a00-a6b4-ba95f865d644",
        "partitions": [
          {
            "name": "Fact Plan",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactPlan",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Deal",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DealID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e70aacd4-29ec-4cb9-933f-4cd4218f581d",
            "sourceColumn": "DealID",
            "summarizeBy": "none"
          },
          {
            "name": "DealName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93b1be8b-0538-42d4-96c9-b2aea2c68cbf",
            "sourceColumn": "DealName",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21b17641-c104-420b-bfef-2a346dfff369",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "DealStateName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "260d408f-0b9d-402f-9694-67b4dbd2118f",
            "sourceColumn": "DealStateName",
            "summarizeBy": "none"
          },
          {
            "name": "DealStatePipeline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4542a9c1-f0d7-405d-81c9-fc35ecd533cc",
            "sourceColumn": "DealStatePipeline",
            "summarizeBy": "none"
          },
          {
            "name": "DealPlannedDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "30edb36b-a5dc-4a9a-b3d5-e80f17ea330c",
            "sourceColumn": "DealPlannedDays",
            "summarizeBy": "none"
          },
          {
            "name": "LastChangedDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8dad8681-cf52-4db2-bcb4-1118fb798b52",
            "sourceColumn": "LastChangedDateID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "114e1839-eabe-425d-ae87-93cac5fd2707",
        "partitions": [
          {
            "name": "Dim Deal",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimDeal",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Budget",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "13e22fa9-1c56-4dc4-8505-6837eb2854bd",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "Attribut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4540e795-62c2-4f44-90ed-53e8dfb2902b",
            "sourceColumn": "Attribut",
            "summarizeBy": "none"
          },
          {
            "name": "Wert",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"\";-#,0.00\\ \"\";#,0.00\\ \"\"",
            "isHidden": true,
            "lineageTag": "5cba20d5-db9a-4c99-9fb8-0572edaf07be",
            "sourceColumn": "Wert",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4827fed5-1ff7-4b3f-b316-24a4fcf22ad3",
        "partitions": [
          {
            "name": "Fact Budget",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactBudget,",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Projektbudget\", Currency.Type}, {\"Rechnungen (abgerechnet)\", Currency.Type}, {\"verbleibendes Projektbudget (abgerechnet)\", Currency.Type}, {\"Rechnungen (nicht abgerechnet)\", Currency.Type}, {\"verbleibendes Projektbudget (nicht abgerechnet)\", Currency.Type}, {\"geplant in Jira\", Currency.Type}, {\"geplant in TM1\", Currency.Type}, {\"verbleibendes Projektbudget (ungeplant)\", Currency.Type}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"BlueAntProjectID\"}, \"Attribut\", \"Wert\")",
                "in",
                "    #\"Unpivoted Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Budget Days",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "04826027-ffad-466b-a7d0-433d228bdede",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "Attribut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c9b58290-1eae-49c4-8bd5-3278a9c012a4",
            "sourceColumn": "Attribut",
            "summarizeBy": "none"
          },
          {
            "name": "Wert",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "93b9bc8f-b2f1-4b7b-b865-a48dacf6d171",
            "sourceColumn": "Wert",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "07e2343c-6c79-4a4a-9412-3b8f45102772",
        "partitions": [
          {
            "name": "Fact Budget Days",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = vw_FactBudgetDays,",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(Source, {\"BlueAntProjectID\"}, \"Attribut\", \"Wert\")",
                "in",
                "    #\"Unpivoted Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Budget Category",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SortId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bc3cfb4b-fc4c-4c98-b080-9e26ca9e3e13",
            "sourceColumn": "SortId",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c049f72-834d-4ced-9889-dc75f7a2e282",
            "sortByColumn": "SortId",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1fc52003-4425-4140-a5b7-1af6f8b78047",
        "partitions": [
          {
            "name": "Dim Budget Category",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hY7LCsIwEEV/JcxKoZv69hcEQcRdyCJpr2lsGSWmfr9JVlqFLHO450ykpDOajke2YDHTxsKnN8KcKlqQqiS94M0AZ8AtnuLk7zf0wYytRfgxltn4TLJruiAms1U5/NdbZ8/iMWgOwrE4OK8j30z55VhHvCufSb/MVspv8/5rEWldrlw9XArsSak3\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, SortId = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Category\", type text}, {\"SortId\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Jira Issue",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "JiraIssueID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c58e152b-e7cd-4486-8f7c-26dad5b4bb13",
            "sourceColumn": "JiraIssueID",
            "summarizeBy": "none"
          },
          {
            "name": "ParentJiraIssueID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "05d4da1e-3e60-4ad5-aa7b-8074249b89fc",
            "sourceColumn": "ParentJiraIssueID",
            "summarizeBy": "none"
          },
          {
            "name": "JiraIssue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38a2cd36-6293-4426-aec0-b2a119016e69",
            "sourceColumn": "JiraIssue",
            "summarizeBy": "none"
          },
          {
            "name": "JiraIssueName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3752da58-c87b-43a1-89f8-0c3671927c9f",
            "sourceColumn": "JiraIssueName",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "94c6abf7-c690-4654-bfae-8ea15db6237b",
            "sourceColumn": "UserID",
            "summarizeBy": "none"
          },
          {
            "name": "JiraSprintID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a512a9ab-39ad-412c-bc41-ce93db4d7789",
            "sourceColumn": "JiraSprintID",
            "summarizeBy": "none"
          },
          {
            "name": "JiraIssueType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a83ebcbc-71da-4c94-ba2c-57c0c9b424e5",
            "sourceColumn": "JiraIssueType",
            "summarizeBy": "none"
          },
          {
            "name": "BlueAntProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d72ab456-85e6-4170-8ed1-0568a7d7359a",
            "sourceColumn": "BlueAntProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "JiraIssuePath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "PATH('Dim Jira Issue'[JiraIssueID], 'Dim Jira Issue'[ParentJiraIssueID])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "65b26fed-4792-47ed-a8c7-86c16aba9c74",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "JiraIssue L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR _level = PATHITEM('Dim Jira Issue'[JiraIssuePath], 1)",
              "RETURN",
              "    LOOKUPVALUE('Dim Jira Issue'[JiraIssue],'Dim Jira Issue'[JiraIssueID], _level)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a36eaef3-ab98-4eab-adbc-1b7e139b5afb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "JiraIssue L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR _level = PATHITEM('Dim Jira Issue'[JiraIssuePath], 2)",
              "RETURN",
              "    LOOKUPVALUE('Dim Jira Issue'[JiraIssue],'Dim Jira Issue'[JiraIssueID], _level)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "797a73f3-1cc0-4d21-826c-1f5876412527",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "JiraIssue L3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    VAR _level = PATHITEM('Dim Jira Issue'[JiraIssuePath], 3)",
              "RETURN",
              "    LOOKUPVALUE('Dim Jira Issue'[JiraIssue],'Dim Jira Issue'[JiraIssueID], _level)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7a773ada-e0e3-47bd-a679-979505a37213",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "819cb8e6-7b53-4254-9d74-5de8502eb7bd",
        "partitions": [
          {
            "name": "Dim Jira Issue",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimJiraIssue",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Sprint Visualiation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "JiraSprintID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fd84b30a-a935-46fb-9069-7b6d45bcd913",
            "sourceColumn": "JiraSprintID",
            "summarizeBy": "none"
          },
          {
            "name": "SprintName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14973581-06a1-4647-996e-bc47742a65eb",
            "sourceColumn": "SprintName",
            "summarizeBy": "none"
          },
          {
            "name": "SprintNameShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09236652-a5c9-410a-91f5-9dbadd868376",
            "sourceColumn": "SprintNameShort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6759002b-6eb6-41ed-9e18-9ec29820c175",
        "partitions": [
          {
            "name": "Dim Sprint Visualiation",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = vw_DimSprint",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Helper Duplikate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TableSchema",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcee97b1-7fd9-4c39-8691-a7358158831d",
            "sourceColumn": "TableSchema",
            "summarizeBy": "none"
          },
          {
            "name": "TableName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae984ec4-e9b0-4c33-a5ef-0398e8ab7fd9",
            "sourceColumn": "TableName",
            "summarizeBy": "none"
          },
          {
            "name": "HitDuplicateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49a80264-ad33-4e04-a38b-692bde815225",
            "sourceColumn": "HitDuplicateKey",
            "summarizeBy": "count"
          },
          {
            "name": "SumDuplicates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b14f9a9a-0fb4-4481-b611-bba2652137db",
            "sourceColumn": "SumDuplicates",
            "summarizeBy": "sum"
          },
          {
            "name": "ManuallyOverwritten",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5fd2efb-eaa4-432c-861d-7e040a1cb452",
            "sourceColumn": "ManuallyOverwritten",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f42768f4-c92a-41fe-97e5-f87ba1c98ee5",
        "partitions": [
          {
            "name": "Helper Duplikate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sql-dwh-prod-gt4645g.database.windows.net\", \"sqldb-dwh-prod-gt4645g\", [Query=\"SELECT #(lf)#(tab)TableSchema#(lf)#(tab),TableName#(lf)#(tab),HitDuplicateKey#(lf)#(tab),SumDuplicates#(lf)#(tab),CONVERT(#(lf)#(tab)#(tab)SMALLINT#(lf)#(tab)#(tab),CASE #(lf)#(tab)#(tab)#(tab)WHEN TableName in ('DimUser','DimBlueAntAbsenceType','DimBlueAntUser','DimJiraSprint') THEN 1 #(lf)#(tab)#(tab)#(tab)ELSE 0#(lf)#(tab)#(tab)END#(lf)#(tab)) ManuallyOverwritten#(lf)FROM logging.HashkeyBkDuplikatsStatus#(lf)WHERE IsDeleted = 0#(lf)#(tab)AND HitDuplicateKey > 0\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}