CREATE TABLE [dwh].[DimDate] (
    [DateID]               INT          NOT NULL,
    [DateBK]               DATE         NOT NULL,
    [DateText]             CHAR (10)    NOT NULL,
    [DayID]                INT          NOT NULL,
    [DayText]              VARCHAR (2)  NOT NULL,
    [MonthID]              INT          NOT NULL,
    [MonthText]            VARCHAR (2)  NOT NULL,
    [QuarterID]            INT          NOT NULL,
    [QuarterText]          VARCHAR (2)  NOT NULL,
    [YearID]               INT          NOT NULL,
    [CalendarWeekID]       INT          NOT NULL,
    [CalendarWeekText]     VARCHAR (2)  NOT NULL,
    [CalendarWeekYearText] VARCHAR (7)  NOT NULL,
    [CalendarYearID]       INT          NOT NULL,
    [MonthNameDE]          VARCHAR (9)  NOT NULL,
    [MonthShortNameDE]     VARCHAR (3)  NOT NULL,
    [MonthNameEN]          VARCHAR (9)  NOT NULL,
    [MonthShortNameEN]     VARCHAR (3)  NOT NULL,
    [WeekdayID]            INT          NOT NULL,
    [WeekdayNameDE]        VARCHAR (10) NOT NULL,
    [WeekdayShortNameDE]   VARCHAR (2)  NOT NULL,
    [WeekdayNameEN]        VARCHAR (9)  NOT NULL,
    [WeekdayShortNameEN]   VARCHAR (2)  NOT NULL,
    [DayOfYear]            INT          NOT NULL,
    [YearMonthID]          INT          NOT NULL,
    [IsEndOfMonth]         SMALLINT     NOT NULL,
    [IsWeekend]            SMALLINT     NOT NULL,
    [FirstDayOfWeek]       INT          NOT NULL,
    [LastDayOfWeek]        INT          NOT NULL,
    [LastDayOfMonth]       INT          NOT NULL,
    [DaysInMonth]          INT          NOT NULL
);

